#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

if [ ! -d $OPENSHIFT_DATA_DIR/media ]; then
    mkdir $OPENSHIFT_DATA_DIR/media
fi
 
ln -sf $OPENSHIFT_DATA_DIR/media $OPENSHIFT_REPO_DIR/wsgi/static/media

if [ ! -e $OPENSHIFT_DATA_DIR/pre_start_python ]; then
	ln -sf $OPENSHIFT_DATA_DIR/pre_start_python $OPENSHIFT_REPO_DIR/.openshift/action_hooks/pre_start_python
fi

source ${OPENSHIFT_PYTHON_DIR}virtenv/bin/activate
${OPENSHIFT_PYTHON_DIR}virtenv/bin/pip install --use-mirrors -r ${OPENSHIFT_REPO_DIR}appsembler-launch/requirements/production.txt
