#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.
source ${OPENSHIFT_PYTHON_DIR}virtenv/bin/activate
 
source ${OPENSHIFT_DATA_DIR}secret_keys

echo "Starting celery worker"
CELERY_RUNNING=$(ps -ef | grep "celery" | grep -v "grep" | wc -l)
echo $CELERY_RUNNING

if [ $CELERY_RUNNING -eq 0 ]
then
    NEW_RELIC_CONFIG_FILE=${OPENSHIFT_DATA_DIR}newrelic.ini newrelic-admin run-python "$OPENSHIFT_REPO_DIR"appsembler-launch/openshift_deploy/manage.py celeryd -l warning -B --autoscale=6,3 --settings=openshift_deploy.settings.production >> $OPENSHIFT_PYTHON_LOG_DIR/celery.log 2>&1 &
fi

echo "Starting flower"
python "$OPENSHIFT_REPO_DIR"appsembler-launch/openshift_deploy/manage.py celery flower --settings=openshift_deploy.settings.production --port=5445 --address=${OPENSHIFT_PYTHON_IP} -s ${OPENSHIFT_DATA_DIR}celerybeat --broker=redis://:${REDIS_PASSWORD}@${OPENSHIFT_REDIS_HOST}:${OPENSHIFT_REDIS_PORT}/0 >> $OPENSHIFT_PYTHON_LOG_DIR/flower.log 2>&1 &
